In [1]:
print("Hello World")

Hello World


In [5]:
a=19
a

19

In [2]:
import numpy as np

In [3]:
#array using list
ls=[1,2,3,4,5]
arr=np.array(ls)
arr

array([1, 2, 3, 4, 5])

In [7]:
#square of list
sq_ls=[]
for i in ls:
    sq_ls.append(i**2)
sq_ls

[1, 4, 9, 16, 25]

In [8]:
ls*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
arr*2

array([ 2,  4,  6,  8, 10])

In [10]:
#List comprehension
[x**2 for x in ls]

[1, 4, 9, 16, 25]

In [11]:
arr1 = np.array((5,3,9,7,1))
arr1

array([5, 3, 9, 7, 1])

In [12]:
arr2 = np.array(["Hema","Rekha","Jaya","Sushma"])
arr2

array(['Hema', 'Rekha', 'Jaya', 'Sushma'], dtype='<U6')

In [13]:
arr3 = np.array(["Ram","Sita",1,0])
arr3

array(['Ram', 'Sita', '1', '0'], dtype='<U11')

In [15]:
arr4 = np.arange(1,1001,50)
arr4

array([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601,
       651, 701, 751, 801, 851, 901, 951])

In [16]:
arr5 = np.arange(23)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [17]:
arr6 = np.arange(2,6)
arr6

array([2, 3, 4, 5])